version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: ./docker/development/django/Dockerfile
    command: /start
    container_name: django-api
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/mediafiles
    ports:
      - "8000:8000"
    expose:
      - "8000"
    env_file:
      - ./.envs/.development/.django
      - ./.envs/.development/.postgres
    depends_on:
      - postgres
      - mailhog
    networks:
      - modern-blog-api

  postgres:
    build:
      context: .
      dockerfile: ./docker/development/postgres/Dockerfile
    container_name: postgres
    volumes:
      - development_postgres_data:/var/lib/postgresql/data
      - development_postgres_data_backups:/backups
    env_file:
      - ./.envs/.development/.postgres
    networks:
      - modern-blog-api

  mailhog:
    image: mailhog/mailhog:v1.0.0
    container_name: mailhog
    ports:
      - "8025:8025"
    networks:
      - modern-blog-api

networks:
  modern-blog-api:
    driver: bridge

volumes:
  development_postgres_data: {}
  development_postgres_data_backups: {}
  static_volume:
  media_volume:
