# Generated by Django 3.2.11 on 2024-03-17 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='facebook_handle',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='github_handle',
        ),
        migrations.AddField(
            model_name='profile',
            name='facebook_account',
            field=models.CharField(blank=True, max_length=20, verbose_name='facebook_account'),
        ),
        migrations.AddField(
            model_name='profile',
            name='github_account',
            field=models.CharField(blank=True, max_length=20, verbose_name='twitter_account'),
        ),
    ]
