# Generated by Django 3.2.11 on 2024-03-17 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20240317_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_photo',
            field=models.ImageField(blank=True, upload_to='', verbose_name='profile photo'),
        ),
    ]
