#!/bin/bash

# Exit immediately if a command exits with a non-zero status
set -o errexit
# Treat unset variables as an error when substituting
set -o nounset

# Automatically restart Celery worker when Python files in modern_blog_api/ directory change
watchmedo auto-restart -d modern_blog_api/ -p '*.py' -- celery -A modern_blog_api worker --loglevel=info
