#!/usr/bin/env bash
# script for listing all backups 
 
set -o errexit
set -o pipefail
set -o nounset

working_dir="$(dirname ${0})"
source "${working_dir}/_sourced/constants.sh"
source "${working_dir}/_sourced/messages.sh"

message_welcome "Listing all backups"

ls -lht "${BACKUP_DIR_PATH}"